### ISSUE TITLE
Optimal price point

### ISSUE THREAD

**Issue by Shukker** [alletsee/pricesensitivitymeter#8]
Hi,

this is my output: 
<img width="336" alt="grafik" src="https://user-images.githubusercontent.com/40241723/41361594-b77c2c6c-6f2f-11e8-87f3-fc8979690688.png">

Lower bound equals optimal price point?

**Comment by alletsee** [comment]
Hi,

Thanks for raising the issue. I just re-checked the code and both the summary function and the definitions of the price points look correct. 

Based on the PSM model, it is certainly possible that the lower bound of the acceptable price range and the optimal price point are equal. The lower bound of the acceptable price range is defined as the intersection of "too cheap" and "expensive". The optimal price point is defined as the intersection of "too cheap" and "too expensive". If your "expensive" and your "too expensive" curves are very similar in this price region, this might be the main reason. Note that small sample sizes and/or price steps in this area may make this scenario more likely.

It's hard to judge without seeing your raw data. I would suggest to graphically inspect the "expensive" and the "too expensive" curve. You can find the output data in OUTPUT$data_vanwestendorp.
Please let me know if this helps you to solve the issue or not. If not, I am happy to discuss other ways how to make sense of the situation.

**Comment by Shukker** [comment]
... one example:

<img width="502" alt="grafik" src="https://user-images.githubusercontent.com/40241723/41408515-3f4087d0-6fd3-11e8-845a-7fbd1367a9d3.png">

Output (always lower limit = optimal price point):

<img width="336" alt="grafik" src="https://user-images.githubusercontent.com/40241723/41408558-63f7e1b8-6fd3-11e8-81dd-2effe4f8bfe6.png">

**Comment by Shukker** [comment]
It works now - thank you once again!

**Comment by alletsee** [comment]
Hi Shukker,
Thanks again for the note and for the explanation. I will take a deeper look based on your example with random data mentioned above - however, I am almost sure that it is related to the nature of the price curves. The R code to identify the different price points is fairly simple and clean, so i am quite certain that this is not a bug. Will keep on investigating.

**Comment by alletsee** [comment]
I recently had time to check your example. Being aware that Shukker solved the issue on himself/herself, I wanted to summarize the solution to this problem.

To identify the different price points, the package uses the which() function from base R. I am not aware of any packages that override this function, and I just cross-checked it for stringi: stringi does not interfere with this. In other words, it is not a bug and the function works as intended.

I cross-checked the random data that you provided and indeed the problem is the steepness of the price curves. Below is a picture that shows the "too cheap", the "expensive" and the "too expensive" price curves just before the OPP (which is the green triangle). Both the "expensive" and the "too expensive" function are exactly zero in this price range. This also means that both functions are exactly identical in this price range. The "too cheap" function drops until it reaches zero at the OPP. In other words, all three function have the value 0 at this price - which explains why this is both the OPP and the lower end of the acceptable price range. So in fact the R function/package is consistent with the way how the different points are described in the original van Westendorp paper.

![github issue 8 - psm plot](https://user-images.githubusercontent.com/6639488/41811975-02c9f144-771a-11e8-959d-0849bbc85f6e.png)

I agree that his might not be very meaningful in this extreme case - however, I have never seen before that actual respondents have provided such extreme answers. (The randomized data is constructed in a way that price preferences are almost identical across respondents and have basically extreme price steps between the prices. For instance, there is price information for up to 6.48 followed by a gap until 16.91, which is just before the end of the acceptable price range.)

Note that the steepness of the example data also explains why the upper end of the acceptable price range is identical to the IDP.
